version: '3.8'

services:
  susradar-server:
    build: .
    container_name: susradar-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key-in-production}
      - DATA_DIR=/app/data
      - JWT_EXPIRATION_HOURS=24
      - PORT=5000
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - susradar-network

networks:
  susradar-network:
    driver: bridge

volumes:
  susradar-data:
    driver: local